[de APP_INFO
  ("name"      "picolisp-posixmq")
  ("version"   "0.1.0")
  ("summary"   "POSIX Message Queues library for PicoLisp (64-bit only)")
  ("source"    "https://github.com/aw/picolisp-posixmq")
  ("author"    "Alexander Williams")
  ("license"   "MIT")
  ("copyright" "(c) 2020 Alexander Williams, On-Prem <license@on-premises.com>")
  ("requires"
    ("picolisp-unit"   "v3.1.0"      "https://github.com/aw/picolisp-unit.git") ]
